/**
 * Request a security token from the server
 * @return {string} security token generated by the server
 */
function getToken() {
    var request = new XMLHttpRequest();
    request.open("GET", "_assets/php/getToken.php", false);
    request.send();
    // request.onreadystatechange = function() {
    //     if (this.readyState == 4 && this.status == 200) {
    //         response = request.responseText;
    //     }
    // };

    return request.responseText;
}

document.addEventListener("DOMContentLoaded", function () {
    var token = getToken();
    console.log(token);
}, false);